/*
-- Query: SELECT * FROM rohinicomplex.asset
LIMIT 0, 1000

-- Date: 2017-02-12 12:04
*/
INSERT INTO `asset` (`ID`,`GARRIAGEID`,`FLATID`,`ASSETTYPEID`) VALUES (1,1,NULL,2);
INSERT INTO `asset` (`ID`,`GARRIAGEID`,`FLATID`,`ASSETTYPEID`) VALUES (2,NULL,35,1);
