/*
-- Query: SELECT * FROM rohinicomplex.role
LIMIT 0, 1000

-- Date: 2017-02-12 12:11
*/
INSERT INTO `role` (`ID`,`NAME`,`DISPLAY_NAME`,`RETIRED`,`CONTRL`) VALUES (1,'ADMIN','ADMIN',0,0);
INSERT INTO `role` (`ID`,`NAME`,`DISPLAY_NAME`,`RETIRED`,`CONTRL`) VALUES (2,'PRESIDENT','PRESIDENT',0,0);
INSERT INTO `role` (`ID`,`NAME`,`DISPLAY_NAME`,`RETIRED`,`CONTRL`) VALUES (3,'SECRETARY','SECRETARY',0,0);
INSERT INTO `role` (`ID`,`NAME`,`DISPLAY_NAME`,`RETIRED`,`CONTRL`) VALUES (4,'TREASURER','TREASURER',0,0);
INSERT INTO `role` (`ID`,`NAME`,`DISPLAY_NAME`,`RETIRED`,`CONTRL`) VALUES (5,'OWNER','OWNER',0,0);
INSERT INTO `role` (`ID`,`NAME`,`DISPLAY_NAME`,`RETIRED`,`CONTRL`) VALUES (6,'TENANT','TENANT',0,0);
INSERT INTO `role` (`ID`,`NAME`,`DISPLAY_NAME`,`RETIRED`,`CONTRL`) VALUES (7,'RELATIVE','RELATIVE',0,0);
INSERT INTO `role` (`ID`,`NAME`,`DISPLAY_NAME`,`RETIRED`,`CONTRL`) VALUES (8,'SYSTEM','SYSTEM',0,0);
