/*
-- Query: SELECT * FROM rohinicomplex.userdocumenttype
LIMIT 0, 1000

-- Date: 2017-02-12 12:11
*/
INSERT INTO `userdocumenttype` (`ID`,`NAME`,`DESCRIPTION`,`CODE`,`RETIRED`) VALUES (1,'IDENTITYPROOF','IDENTITY PROOF','IDPROOF',0);
INSERT INTO `userdocumenttype` (`ID`,`NAME`,`DESCRIPTION`,`CODE`,`RETIRED`) VALUES (2,'ADDRESSPROOF','ADDRESS PROOF','ADDRPROOF',0);
INSERT INTO `userdocumenttype` (`ID`,`NAME`,`DESCRIPTION`,`CODE`,`RETIRED`) VALUES (3,'OCCUPATION','OCCUPATION','OCCUPATION',0);
