/*
-- Query: SELECT * FROM rohinicomplex.videtype
LIMIT 0, 1000

-- Date: 2017-02-12 12:12
*/
INSERT INTO `VIDETYPE` (`ID`,`NAME`,`DESCRIPTION`,`CODE`,`RETIRED`) VALUES (1,'CASH','CASH','CASH',0);
INSERT INTO `VIDETYPE` (`ID`,`NAME`,`DESCRIPTION`,`CODE`,`RETIRED`) VALUES (2,'BANKDEPOSIT','BANK DEPOSIT','EFT',0);
INSERT INTO `VIDETYPE` (`ID`,`NAME`,`DESCRIPTION`,`CODE`,`RETIRED`) VALUES (3,'CHEQUE','CHEQUE','CHEQUE',0);
